<?php
return [
    // 25.0
    'plan_management' => 'Plan under management',
    'promotion_settings' => 'Promotion settings',
    'plan_registration' => 'Plan registration',

    'first_description' => 'Monthly support by making a plan<br/>Can be received from fans',

    'setting' => 'Setting',
    'add_plant' => 'Add a plan',
    'enable_promotion' => 'Enable promotion',

    // 25.1
    'plan_name' => 'Plan name',
    'fee' => 'Monthly fee',
    'plan_description' => 'Plan description',
    'creator_gerne' => 'Creator genre',
    'viewing' => 'Viewing restrictions',
    'set_number' => 'Set back number sales',

    'add_plan_name' => 'Add a plan name',
    'add_plan_description' => 'Add plan description',
    'include_content' => 'Includes content with a viewing age limit',

    'second_description' => 'Back numbers are closed at the end of every month for posts posted on the plan.<br/>It is a function that can be sold collectively by the posting month.<br/><br/>(Purchase is only possible for supporters who have subscribed to the plan.<br/>vinegar. )<br/><br/>This back number is "Purchaser" and "Plan supporter of the corresponding month"<br/>It is possible to browse at.<br/><br/>(Example: Supporters who joined in March 2022 will continue in April 2022.<br/>It is possible to view the March posts. Non-supporters are Bucknan<br/>You cannot browse without purchasing the bar. )<br/><br/>&nbsp Learn more about back numbers',

    // 25.2
    'third_description' => 'CucuruFans Promotion Details<br/><br/>With cucurucrew promotion,<br/>Industry-leading affiliate with high advertising power<br/>Will promote your page.<br/><br/>The reward for affiliates is 20% of the total.<br/><br/>This reward is deducted from 80% of you and paid to the affiliator<br/>Will be. (Your reward via affiliate is a seller<br/>It will be 60% of the product. )<br/><br/><br/>Promotional requirements<br/><br/>・ The reward generated through referrals from affiliates is 60%.<br/>increase. The remaining 20% ​​will be paid to the affiliate.<br/><br/>・ Subscription renewed via referral of affiliate<br/>If it is done, the same reward will be applied.<br/><br/>・ Affiliates can introduce monthly support and individual sales<br/>There are only two for sale.<br/><br/><br/>CandFans Promotion Terms and Conditions<br/><br/>・ Creators participating in the CandFans promotion<br/>I was able to receive 20% of the sales generated by introducing<br/>vinegar.<br/><br/>・ In addition, users will subscribe to the creators you introduced.<br/>You will receive 20% of your sales forever as long as you continue to cry<br/>come.',
    'check_box' => 'I am over 18 years old<br/>I agree to the above terms of use and privacy policy',
    'enable' => 'Enable promotion',
];
