<?php
return [
    // 25.0
    'page_title' => 'Plan under management',
    'page_title_1' => 'Plan registration',
    'page_title_2' => 'Promotion settings',

    'plan_management' => 'Plan under management',
    'promotion_settings' => 'Promotion settings',
    'plan_registration' => 'Plan registration',

    'first_description' => 'Monthly support by making a plan\nCan be received from fans',

    'setting' => 'Setting',
    'add_plant' => 'Add a plan',
    'enable_promotion' => 'Enable promotion',

    // 25.1
    'plan_name' => 'Plan name',
    'fee' => 'Monthly fee',
    'plan_description' => 'Plan description',
    'creator_gerne' => 'Creator genre',
    'viewing' => 'Viewing restrictions',
    'set_number' => 'Set back number sales',

    'add_plan_name' => 'Add a plan name',
    'add_plan_description' => 'Add plan description',
    'include_content' => 'Includes content with a viewing age limit',

    'second_description' => 'Back numbers are closed at the end of every month for posts posted on the plan.\nIt is a function that can be sold collectively by the posting month.\n(Purchase is only possible for supporters who have subscribed to the plan.\nvinegar. )\nThis back number is "Purchaser" and "Plan supporter of the corresponding month"\nIt is possible to browse at.\n(Example: Supporters who joined in March 2022 will continue in April 2022.\nIt is possible to view the March posts. Non-supporters are Bucknan\nYou cannot browse without purchasing the bar. )\n&nbsp Learn more about back numbers',

    // 25.2
    'third_description' => 'CucuruFans Promotion Details\nWith CucuruFans promotion,\nIndustry-leading affiliate with high advertising power\nWill promote your page.\nThe reward for affiliates is 20% of the total.\nThis reward is deducted from 80% of you and paid to the affiliator\nWill be. (Your reward via affiliate is a seller\nIt will be 60% of the product. )\nPromotional requirements\n・ The reward generated through referrals from affiliates is 60%.\nincrease. The remaining 20% ​​will be paid to the affiliate.\n・ Subscription renewed via referral of affiliate\nIf it is done, the same reward will be applied.\n・ Affiliates can introduce monthly support and individual sales\nThere are only two for sale.\nCandFans Promotion Terms and Conditions\n・ Creators participating in the CandFans promotion\nI was able to receive 20% of the sales generated by introducing\nvinegar.\n・ In addition, users will subscribe to the creators you introduced.\nYou will receive 20% of your sales forever as long as you continue to cry\ncome.',
    'check_box' => 'I am over 18 years old\nI agree to the above terms of use and privacy policy',
    'enable' => 'Enable promotion',
];
